### ISSUE TITLE
Footprint request: TO-5 10-pin

### ISSUE THREAD

**Issue by Fat-Zer** [KiCad/TO_SOT_Packages_THT.pretty#10]
The request is just QA issue due to symbol linear library includes one component (LM733CH) which is available only in this case.

This issue may be considered as a memo/TODO.

**Comment by evanshultz** [comment]
Since this issue was rasied, this footprint has been created at https://github.com/KiCad/TO_SOT_Packages_THT.pretty/blob/master/TO-5-10.kicad_mod. Closing.
