### ISSUE TITLE
Multiwatt packages don't have "TO-220" in footprint name

### ISSUE THREAD

**Issue by evanshultz** [KiCad/TO_SOT_Packages_THT.pretty#26]
TO-220 footprints are in the lib for 2 through 9 leads. (More than 3 leads is a stretched TO-200, but still recognizable as a TO-220 package.) Some of them are also called "Multiwatt", which as far as I can tell is only used by STMicro.

However, the 11- and 15-pin TO-220 packages are _only_ called Multiwatt. Why? Is there a reason? TO-220 is the generic package name which would bring them all together.

If nobody knows a reason for this, I propose we add `TO-220-11_` or `TO-220-15_` to the front of the 11- and 15-pin footprints to make them consistent and grouped with all the other TO-220 footprints. Agree?

**Comment by jkriege2** [comment]
maybe we can even remove the multiwatt from the name completely (I think it ended up there partly due to historic reasons and partly because I only found datasheets that calls them multiwatt ... note that e.g. for the pentawatts/TO-220-5 it's different).

I would propose to either:
- rename in the scheme as the other TO-220-X
- rename all of them to only have TO-220-XX and the alternative names only in the description

In both cases we'll need to ensure to also fix all FPFIlters and footprint-fields!

Best,
JAN

**Comment by evanshultz** [comment]
Thanks for the comments, Jan. (And I hope your vacation is fun and relaxing!) I like the second option. It simplifies the footprints names greatly, but we still have terms like "Multiwatt" somewhere in the metadata that can be searched.

The footprint name would be like `TO-220-15_Vertical_Staggered1`. Since lead prep has no standard terms that I know of, using a number is fine. And while "Staggered" could be changed to "Prep" or something, at least for now it's description and doesn't bother me.

If nobody objects by the time I get to it, I'll do this along with a PR that I'm submitting to this repo soon.

**Comment by evanshultz** [comment]
One problem with this: How would we differentiate between a TO-220 with >3 leads all in a row and one that has the same number of leads staggered? For example, http://www.st.com/resource/en/datasheet/tda7264.pdf and 8 leads all in one row while https://ac-dc.power.com/sites/default/files/product-docs/topswitch-hx_family_datasheet.pdf has 7 leads on a normal TO-220 body (I know we have a specific library for Power Integrations parts).

These aren't perfect counterpoints, but they show that lead prep could allow the same lead count but with quite different footprints.

Perhaps `TO-220-8W_Vertical` for the first link, using `W` to indicate "wide body" as we do with SOICs? Then the other package could be `TO-220-7_Vertical_Staggered1`? I'm good with that. Or should the the outer package dimensions be given to differentiate them?

**Comment by poeschlr** [comment]
My suggestion: (Similar to other packages. Main difference to the suggestion by @evanshultz: orientation is near the end like it is currently in other types of packages.)
I would interpret the staggered option as be part of my suggested `pad modifier` options. (See https://github.com/KiCad/kicad-library/issues/1447)

Instead of `W` for wide body i would give the body dimensions in the name (like we do with other footprints.) 
The W in soic currently is not a good identifier. Just take a look at the 16 pin variant. There is a 16W that is 5.3mm wide and a 16W that is 7.5mm wide.

---

`{[Manufacturer name]_}[package name]-[pin count]{_[Size x]x[Size y]{x[Height]}mm}{_Pitch[pitch x]{x{pitch y}}}{_[Staggered1 | Staggered2]}{_Lead[Lead length]}{_Pad[pad length]{x[pad width]}}_[Tab-Down | Vertical | Tab-Up]{_footprint options}`

Staggered:
 - Type 1 (Staggered1): Odd pins far away from package body
 - Type 2 (Staggered2): Even pins far away from package body

Orientation:
<img src="https://user-images.githubusercontent.com/18327350/29744904-8b954720-8aae-11e7-8d46-3d68bb475bec.png" width=50%/>

Size parameters:
![body_dim_s](https://user-images.githubusercontent.com/18327350/29736904-044a0e0c-8a06-11e7-9634-ba4d1151ad5b.png)
The lead length is always measured for pin 1

---

Edit: Orientation names as suggested by @evanshultz

**Comment by evanshultz** [comment]
Yes, this is a great start. I need to think about this a bit more in case there are edge cases.

I've used `TabUp` and `TabDown` for the horizontal orientations before. That gives a non-ambiguous understanding from the footprint name, since `Inverted` or `Reverse` doesn't capture the absolute orientation (they're both relative terms).

**Comment by poeschlr** [comment]
Good idea.
I think we should go with `Tab-Up` and `Tab-Down`. (Easier to read)

**Comment by evanshultz** [comment]
@poeschlr 
Here are a few things that may need to be added:
- Is Lead Length for a staggered pattern to pin 1 or the farthest lead row to body? We should specify.
- Drill hole is not captured. Some packages [like this one](http://ixapps.ixys.com/DataSheet/98791.pdf), have extra thick leads and need bigger holes. Perhaps `_DrillX.XXmm`?
- What about having copper under the tab for `TabDown` variants? Suggested nomenclature? `_CopperXxYmm`?
- Do `TabUp` parts, by default, have no hole for the tab? We should be clear.
- You may want some way to capture is the package is fullpak (plastic encapsulated) since the 3D model will be different. There's already a good place for it, but perhaps a standard nomenclature?

**Comment by poeschlr** [comment]
Is Lead Length for a staggered pattern to pin 1 or the farthest lead row to body? We should specify.

I did specify it in my post as: measured between body and pin 1. (Below the image. Will add it to the image it self later on.)

Everything else are good points. (I am a bit short on time today. will look at it later.)

**Comment by evanshultz** [comment]
@poeschlr Thanks. I did miss the text below the image.

https://www.fairchildsemi.com/datasheets/FS/FSFR2100.pdf is an interesting package to consider. They name it "9-SIP", but it has characteristics which are captured here. Lead stagger, off pin spacing, etc. While I could agree to put that footprint in `Housings_SIP`, perhaps we should consider if our scheme is able to capture a footprint like this.

@jkriege2 @SchrodingersGat @hackscribble 
It would be nice to get more thoughts and opinions. I believe Rene has put together a nice and robust framework in place here, and if we can review and agree on the loose items we'll be ready to rename parts in this library. Actually renaming footprints should be fine to wait until we have a script to search through the library and identify symbols using the footprints that will be renamed, but at least we'll have clarity on what the new footprint names should be.

**Comment by ghost** [comment]
> `{[Manufacturer name]_}[package name]-[pin count]{_[Size x]x[Size y]{x[Height]}mm}{_Pitch[pitch x]{x{pitch y}}}{_[Staggered1 | Staggered2]}{_Lead[Lead length]}{_Pad[pad length]{x[pad width]}}_[Tab-Down | Vertical | Tab-Up]{_footprint options}`

If `{ }` surrounds optional items, the minimal mandatory name would be `[package name]-[pin count]_[Tab-Down | Vertical | Tab-Up]`, is that right?

Would the other items be added *only* when the package has non-standard dimensions?

In the SMD repo, we add `_TabPin[n]` with two variants per device for TO-252 and TO-263 to show whether the tab is electrically connected to the centre pin or not.  Is this concept relevant to the THT devices?

**Comment by evanshultz** [comment]
@hackscribble I believe so. Perhaps body size should always be included, since we know there is a lot of variation? And yes, the tab connection isn't relevant here. It's always the middle tab unless the package is isolated (in my experience).

@Shackmeister Sorry. I didn't mean to leave anyone off.

**Comment by evanshultz** [comment]
@poeschlr Are you able to take a little time and review the above? Your last post mentioned wanting to spend a bit more time to look at this topic.

Are we all agreeing to use `TO-220-#_` as the prefix and ditch `Multiwatt` in the footprint name? That's most clear to me. As an example, [Digikey's audio amplifier](https://www.digikey.com/products/en/integrated-circuits-ics/linear-amplifiers-audio/742) lineup uses TO-220-x even though the IC vendors may use Multiwatt or some other nomenclature:
![image](https://user-images.githubusercontent.com/1936989/30769002-afaca1c2-9fc5-11e7-8602-e114a2e10038.png)

**Comment by jkriege2** [comment]
fine with me ... when you change the footprint names, please ensure to also fix footprint fields and FPFilters in the lib!

Best
JAN

**Comment by evanshultz** [comment]
@jkriege2 Thanks. That's good with me.

@poeschlr Could you take a look? Any concerns or further thoughts?

**Comment by poeschlr** [comment]
Looks good for me. (At least for now. It seems for v5 we will use shorter fp names.)

**Comment by evanshultz** [comment]
@SchrodingersGat Can you make this canon for KLC v3 on the website? Once that's done I think this can be closed.

**Comment by SchrodingersGat** [comment]
Evan, sorry there's a lot to follow here, what am I making canonical? :)

**Comment by evanshultz** [comment]
Specifically Rene's post above. I'm not sure if this went into the new website for this type of footprint.

**Comment by SchrodingersGat** [comment]
Ah, ok, right. Rene and I are still addressing the footprint naming scheme, so this will certainly make it there.
